=== lip6/Coloane/branches/trunk-tycho/application/core/resources/model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

	<xs:annotation>
  		<xs:documentation xml:lang="en">
   			Model description schema for Coloane.
   			LIP6 / MoVe - Jean-Baptiste Voron
   			http://coloane.lip6.fr
  		</xs:documentation>
 	</xs:annotation>

	<!-- Definition du type d'un attribut graphique -->
	<xs:attributeGroup name="graph">
		<xs:attribute name="xposition" type="xs:string" />
		<xs:attribute name="yposition" type="xs:string" />
	</xs:attributeGroup>

	<!-- Definition du type d'un modele -->
	<xs:complexType name="tmodel">
		<xs:all>
			<xs:element name="nodes" type="tnodes" minOccurs="1"/>
			<xs:element name="arcs" type="tarcs" minOccurs="1"/>
			<xs:element name="attributes" type="tattributes" minOccurs="0" />
			<xs:element name="stickys" type="tstickys" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="formalism" type="xs:string" use="required" />
		<xs:attributeGroup ref="graph" />
	</xs:complexType>
	
	<!-- =========================================== = -->

	<!-- Definition d'un noeud -->
	<xs:complexType name="tnode">
		<xs:sequence>
			<xs:element name="attributes" type="tattributes" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attributeGroup ref="graph" />
		<xs:anyAttribute processContents="lax" />
	</xs:complexType>
	
	<!-- Definition d'un point d'inflexion -->
	<xs:complexType name="tpi">
		<xs:attributeGroup ref="graph" />
	</xs:complexType>

	<!-- Definition d'un arc -->
	<xs:group name="tarcdesc">
		<xs:choice>
			<xs:element name="pi" type="tpi" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="attributes" type="tattributes" minOccurs="0" maxOccurs="1"/>
		</xs:choice>
	</xs:group>
	
	<xs:complexType name="tarc">
		<xs:group ref="tarcdesc" minOccurs="0" maxOccurs="unbounded"></xs:group>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:anyAttribute processContents="lax" />
	</xs:complexType>

	<!-- Definition d'un lien -->
	<xs:complexType name="tlink">
		<xs:attribute name="linkId" type="xs:string" use="required" />
	</xs:complexType>
	
	<!-- Definition d'une note -->
	<xs:group name="tstickydesc">
		<xs:choice>
			<xs:element name="value" type="xs:string" minOccurs="1" />
			<xs:element name="link" type="tlink" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:group>
	
	<xs:complexType name="tsticky">
		<xs:group ref="tstickydesc" minOccurs="1" maxOccurs="unbounded"></xs:group>
		<xs:attributeGroup ref="graph" />
		<xs:anyAttribute processContents="lax" />
	</xs:complexType>
	
	<!-- Definition d'un attribut -->
	<xs:complexType name="tattribute">
		<xs:simpleContent>
	 		<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attributeGroup ref="graph" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<!-- ============================================ -->

	<!-- Definition d'un ensemble de noeuds -->
	<xs:complexType name="tnodes">
		<xs:sequence> 
			<xs:element maxOccurs="unbounded" minOccurs="0" name="node" type="tnode"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Definition d'un ensemble d'arcs -->
	<xs:complexType name="tarcs">
		<xs:sequence> 
			<xs:element maxOccurs="unbounded" minOccurs="0" name="arc" type="tarc"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition d'un ensemble de notes -->
	<xs:complexType name="tstickys">
		<xs:sequence> 
			<xs:element maxOccurs="unbounded" minOccurs="0" name="sticky" type="tsticky"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition d'un groupe d'attributs -->
	<xs:complexType name="tattributes">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="attribute" type="tattribute" />
		</xs:sequence>
	</xs:complexType>

	<!-- ============================================ -->

	<!-- Definition d'un modele -->
	<xs:element name="model" type="tmodel"/>
</xs:schema>

=== lip6/Coloane/branches/interfacesResults/itsFormalism/fr.lip6.move.coloane.its/binPhilo.xml
<?xml version='1.0' encoding='UTF-8'?>
<model xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://coloane.lip6.fr/resources/schemas/model.xsd' formalism='ITSComposite' xposition='0' yposition='0'>
<nodes>
<synchronization id='3' name='putRight' label='release' />
<instance id='4' name='p1' type='PhiloFork1' />
<instance id='5' name='p2' type='PhiloFork2' />
</attributes>
</node>
<node nodetype='synchronization' id='6' xposition='596' yposition='109' scale='100' alt='0' foreground='#000000' background='#000000'>
<attributes>
<attribute name='name' xposition='616' yposition='89'>getRight</attribute>
<attribute name='label' xposition='616' yposition='109'>acquire</attribute>
</attributes>
</node>
<node nodetype='synchronization' id='7' xposition='365' yposition='242' scale='100' alt='0' foreground='#000000' background='#000000'>
<attributes>
<attribute name='name' xposition='349' yposition='269'>internalPut</attribute>
</attributes>
</node>
<node nodetype='synchronization' id='8' xposition='372' yposition='109' scale='100' alt='0' foreground='#000000' background='#000000'>
<attributes>
<attribute name='name' xposition='392' yposition='89'>internalGet</attribute>
</attributes>
</node>
<node nodetype='synchronization' id='9' xposition='151' yposition='106' scale='100' alt='0' foreground='#000000' background='#000000'>
<attributes>
<attribute name='name' xposition='171' yposition='86'>getFork</attribute>
<attribute name='label' xposition='171' yposition='106'>getFork</attribute>
</attributes>
</node>
<node nodetype='synchronization' id='10' xposition='154' yposition='242' scale='100' alt='0' foreground='#000000' background='#000000'>
<attributes>
<attribute name='name' xposition='174' yposition='222'>putFork</attribute>
<attribute name='label' xposition='174' yposition='242'>putFork</attribute>
</attributes>
</node>
</nodes>
<arcs>
<arc arctype='arc' id='17' startid='4' endid='10' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='202' yposition='200'>putFork</attribute>
</attributes>
</arc>
<arc arctype='arc' id='16' startid='9' endid='4' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='201' yposition='132'>getFork</attribute>
</attributes>
</arc>
<arc arctype='arc' id='18' startid='4' endid='7' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='308' yposition='200'>release</attribute>
</attributes>
</arc>
<arc arctype='arc' id='11' startid='4' endid='8' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='311' yposition='133'>acquire</attribute>
</attributes>
</arc>
<arc arctype='arc' id='12' startid='5' endid='3' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='524' yposition='202'>release</attribute>
</attributes>
</arc>
<arc arctype='arc' id='13' startid='7' endid='5' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='409' yposition='200'>putFork</attribute>
</attributes>
</arc>
<arc arctype='arc' id='14' startid='8' endid='5' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='412' yposition='133'>getFork</attribute>
</attributes>
</arc>
<arc arctype='arc' id='15' startid='5' endid='6' color='#000000' curved='false'>
<attributes>
<attribute name='labels' xposition='524' yposition='133'>acquire</attribute>
</attributes>
</arc>
</arcs>
<stickys>
</stickys>
</model>
